# Generated by Django 6.0.1 on 2026-01-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=100)),
                ('rank', models.CharField(choices=[('species', 'Species'), ('genus', 'Genus'), ('functional', 'Functional'), ('unknown', 'Unknown')])),
                ('genus', models.CharField(max_length=50)),
                ('nbn_taxon_id', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'taxa',
            },
        ),
    ]
