# Generated by Django 6.0.1 on 2026-02-02 21:34

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('source_id', models.CharField(max_length=40, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('recorded_on', models.DateField()),
                ('recorded_by', models.TextField()),
                ('source', models.CharField(choices=[('ABG', 'Avon Bat Group'), ('BRERC', 'BRERC'), ('NBN', 'NBN'), ('OTHER', 'Other')], max_length=8)),
                ('notes', models.TextField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=27700)),
                ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='records.taxon')),
            ],
            options={
                'ordering': ['-created'],
                'unique_together': {('source', 'source_id')},
            },
        ),
    ]
