# Generated by Django 6.0.1 on 2026-02-02 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_record_imported_by_alter_record_species'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxon',
            options={'ordering': ['scientific_name'], 'verbose_name_plural': 'taxa'},
        ),
    ]
