# Generated by Django 6.0.1 on 2026-01-20 23:13

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('uid', models.UUIDField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('model', models.TextField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('installed_on', models.DateField()),
                ('notes', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspected_on', models.DateField()),
                ('count', models.IntegerField()),
                ('notes', models.TextField()),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='box_checks.box')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('run_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='box',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='box_checks.site'),
        ),
        migrations.AlterUniqueTogether(
            name='box',
            unique_together={('site', 'number')},
        ),
    ]
