# Generated by Django 6.0.1 on 2026-02-02 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('box_checks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='box',
            options={'verbose_name_plural': 'boxes'},
        ),
    ]
