# Generated by Django 6.0.1 on 2026-02-02 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box_checks', '0002_alter_box_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='inspected_on',
        ),
        migrations.AlterField(
            model_name='box',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='box_checks.site'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='box_checks.box'),
        ),
        migrations.AlterField(
            model_name='site',
            name='run_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surveyed_on', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='box_checks.site')),
                ('surveyed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('site', 'surveyed_on')},
            },
        ),
        migrations.AddField(
            model_name='inspection',
            name='survey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='box_checks.survey'),
            preserve_default=False,
        ),
    ]
